# 1 - 02. Numpy

## Numpy

In [2]:
import numpy as np

In [6]:
array = np.array([1,2,3])
print('array type',type(array1))
print('array shape',array1.shape)
print("")

array type <class 'numpy.ndarray'>
array shape (3,)



In [7]:
print("array dimension",array.ndim)
print("array data type",array.dtype)

array dimension 1
array data type int32


In [9]:
array_float = array.astype('float64')
array_float.dtype

dtype('float64')

## ndarray를 편리하게 생성하기

In [16]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.shape)
print(sequence_array.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
1


In [11]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

print(" ")

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
 
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()

In [18]:
array = np.array([[1,2,3],
                [4,5,6]])
print(array, array.shape)

print(" ")

reshape_array = array.reshape(3,2)
print(reshape_array, reshape_array.shape)

print(" ")

reshape_array_1 = array.reshape(1, -1)
print(reshape_array_1, reshape_array_1.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
 
[[1 2]
 [3 4]
 [5 6]] (3, 2)
 
[[1 2 3 4 5 6]] (1, 6)


In [19]:
array_minus_one = array.reshape(-1, 1)
print(array_minus_one, array_minus_one.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

In [25]:
# 특정한 데이터만 추출
array = np.arange(15)
array = array.reshape(3,5)
print(array, array.shape)

print(array[1,2])
print(array[2,3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)
7
13


In [33]:
#슬라이싱(Slicing)
print(array[0:3, 0], array[0:3, 0].shape)
print(array[0, 0:3], array[0, 0:3].shape)
print(array[:-1, :-1], array[:-1, :-1].shape)

[ 0  5 10] (3,)
[0 1 2] (3,)
[[0 1 2 3]
 [5 6 7 8]] (2, 4)


In [34]:
#팬시 인덱싱(Fancy Indexing)
print(array[[0,2], 2], array[[0,2], 2].shape)

[ 2 12] (2,)


In [37]:
#불린 인덱싱(Boolean Indexing)
array_Bool = array[array > 5]
print(array_Bool,array_Bool.shape)
array > 5

[ 6  7  8  9 10 11 12 13 14] (9,)


array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 행렬의 정렬 -sort()와 argsort()

In [50]:
array = np.array([4, 8, 1, 7, 6, 10])

# 오름차순 정렬(1차원)
array1 = np.sort(array)
print(array1)

print(" ")

#내림차순 정렬(1차원)
array2 = np.sort(array)[::-1]
print(array2)

[ 1  4  6  7  8 10]
 
[10  8  7  6  4  1]


In [62]:
array = np.array([4, 2, 1, 3, 7, 12, 14, 5, 0, 6, 9, 11, 13, 10, 8])
array = array.reshape(3,5)
print(array)

print(" ")

#low 방향으로 정렬(2차원 이상)
array1 = np.sort(array, axis = 0)
print(array1)

print(" ")

#column 방향으로 정렬(2차원 이상)
array2 = np.sort(array, axis = 1)
print(array2)

[[ 4  2  1  3  7]
 [12 14  5  0  6]
 [ 9 11 13 10  8]]
 
[[ 4  2  1  0  6]
 [ 9 11  5  3  7]
 [12 14 13 10  8]]
 
[[ 1  2  3  4  7]
 [ 0  5  6 12 14]
 [ 8  9 10 11 13]]


In [63]:
#행렬 정렬 시 원본 행렬의 인덱스 반환
#array = np.array([3, 1, 9, 5])
array_argsort = np.argsort(array)
array_argsort

array([[2, 1, 3, 0, 4],
       [3, 2, 4, 0, 1],
       [4, 0, 3, 1, 2]], dtype=int64)

## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [65]:
A = np.array([[1, 2, 3],
            [4, 5, 6]])
B = np.array([[7, 8],
             [9, 10],
             [11, 12]])

print(np.dot(A, B))

print(" ")

print(np.transpose(A))

[[ 58  64]
 [139 154]]
 
[[1 4]
 [2 5]
 [3 6]]
